# Generated by Django 2.0.5 on 2021-05-14 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField()),
                ('cname', models.CharField(max_length=30)),
                ('cfee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cource',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OneToOne_App.Student'),
        ),
    ]
