# Generated by Django 2.0.5 on 2021-05-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneToOne_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Hyderabad', max_length=50),
        ),
    ]
